# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=300, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('photo_like', models.IntegerField(blank=True, default=0, verbose_name='Количество лайков')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, upload_to='users/%Y/%m/%d', verbose_name='аватар')),
                ('vk_link', models.URLField(verbose_name='ссылка на Vk')),
                ('fb_link', models.URLField(verbose_name='ссылка на facebook')),
                ('twitter_link', models.URLField(verbose_name='ссылка на twitter')),
                ('inst_link', models.URLField(verbose_name='ссылка на instagram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='ProfileManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
