# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('article_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('article_content', models.TextField(verbose_name='Описание')),
                ('article_status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200, verbose_name='Название')),
                ('section_url', models.CharField(max_length=50, verbose_name='ссылка')),
                ('section_description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'section',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.Section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
