# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_status',
            field=models.IntegerField(verbose_name='Статус'),
        ),
    ]
