# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария'),
        ),
    ]
