# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_auto_20171214_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlestatistic',
            options={'verbose_name': 'Статистика просмотров', 'verbose_name_plural': 'Статистики просмотров'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
